// user authentication types
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

// paper controller types
export const CREATE_PAPER_REQUEST = "CREATE_PAPER_REQUEST";
export const CREATE_PAPER_SUCCESS = "CREATE_PAPER_SUCCESS";
export const CREATE_PAPER_FAILED = "CREATE_PAPER_FAILED";

export const GET_PAPER_REQUEST = "GET_PAPER_REQUEST";
export const GET_PAPER_SUCCESS = "GET_PAPER_SUCCESS";
export const GET_PAPER_FAILED = "GET_PAPER_FAILED";

export const GET_SINGLE_PAPER_REQUEST = "GET_SINGLE_PAPER_REQUEST";
export const GET_SINGLE_PAPER_SUCCESS = "GET_SINGLE_PAPER_SUCCESS";
export const GET_SINGLE_PAPER_FAILED = "GET_SINGLE_PAPER_FAILED";

// question controller types 
export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAILED = "CREATE_QUESTION_FAILED";
export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAILED = "GET_QUESTION_FAILED";

// exams controller types
export const CREATE_EXAM_REQUEST = "CREATE_EXAM_REQUEST";
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";
export const CREATE_EXAM_FAILED = "CREATE_EXAM_FAILED";
export const GET_EXAM_REQUEST = "GET_EXAM_REQUEST";
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const GET_EXAM_FAILED = "GET_EXAM_FAILED";

export const GET_EXAMS_BY_DEPARTMENT_REQUEST = "GET_EXAMS_BY_DEPARTMENT_REQUEST";
export const GET_EXAMS_BY_DEPARTMENT_SUCCESS = "GET_EXAMS_BY_DEPARTMENT_SUCCESS";
export const GET_EXAMS_BY_DEPARTMENT_FAILED = "GET_EXAMS_BY_DEPARTMENT_FAILED";



